<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Mini_E_Ticarət_API.Application</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Abstracts\Services\" />
    <Folder Include="Abstracts\Repositories\" />
    <Folder Include="DTOs\" />
    <Folder Include="Validations\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mini E-Ticarət API.Domain\Mini E-Ticarət API.Domain.csproj" />
  </ItemGroup>

</Project>
